# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
 config.vm.box = "centos65"
 config.vm.box_url = "https://github.com/2creatives/vagrant-centos/releases/download/v6.5.1/centos65-x86_64-20131205.box"
 config.vm.network :forwarded_port, guest: 22, host: 2242
 config.vm.network :forwarded_port, guest: 3306, host:3342

config.vm.provision "ansible" do |ansible|
  ansible.playbook = "playbook.yml"
  ansible.sudo = true
end

end
